using TyriaPad.Core.Native;

namespace TyriaPad.Core.Output;

/// <summary>Low-level input target. Exists so the logic can be tested without SendInput.</summary>
public interface IInputSink
{
    void SendKey(Key key, bool down);

    void SendMouseButton(MouseButton button, bool down);

    void SendMouseMove(int dx, int dy);

    void SendMouseWheel(int delta);
}

/// <summary>Emits input with SendInput using scancodes, which GW2 recognizes better than virtual keys.</summary>
public sealed class SendInputSink : IInputSink
{
    /// <summary>Tag in dwExtraInfo to recognize input generated by TyriaPad.</summary>
    public const nint ExtraInfoTag = 0x54504144; // "TPAD"

    public void SendKey(Key key, bool down)
    {
        ushort code = (ushort)key;
        uint flags = User32.KeyEventFScanCode;
        if ((code & 0xFF00) == 0xE000)
        {
            flags |= User32.KeyEventFExtendedKey;
        }

        if (!down)
        {
            flags |= User32.KeyEventFKeyUp;
        }

        User32.Input input = default;
        input.Type = User32.InputKeyboard;
        input.Data.Keyboard.ScanCode = (ushort)(code & 0xFF);
        input.Data.Keyboard.Flags = flags;
        input.Data.Keyboard.ExtraInfo = ExtraInfoTag;
        Send(ref input);
    }

    public void SendMouseButton(MouseButton button, bool down)
    {
        uint flags = (button, down) switch
        {
            (MouseButton.Left, true) => User32.MouseEventFLeftDown,
            (MouseButton.Left, false) => User32.MouseEventFLeftUp,
            (MouseButton.Right, true) => User32.MouseEventFRightDown,
            (MouseButton.Right, false) => User32.MouseEventFRightUp,
            (MouseButton.Middle, true) => User32.MouseEventFMiddleDown,
            _ => User32.MouseEventFMiddleUp,
        };
        SendMouse(flags, 0, 0, 0);
    }

    public void SendMouseMove(int dx, int dy) => SendMouse(User32.MouseEventFMove, dx, dy, 0);

    public void SendMouseWheel(int delta) => SendMouse(User32.MouseEventFWheel, 0, 0, unchecked((uint)delta));

    private static void SendMouse(uint flags, int dx, int dy, uint data)
    {
        User32.Input input = default;
        input.Type = User32.InputMouse;
        input.Data.Mouse.Dx = dx;
        input.Data.Mouse.Dy = dy;
        input.Data.Mouse.MouseData = data;
        input.Data.Mouse.Flags = flags;
        input.Data.Mouse.ExtraInfo = ExtraInfoTag;
        Send(ref input);
    }

    private static unsafe void Send(ref User32.Input input)
    {
        fixed (User32.Input* pointer = &input)
        {
            User32.SendInput(1, pointer, sizeof(User32.Input));
        }
    }
}