using TyriaPad.Core.Output;

namespace TyriaPad.Core.Diagnostics;

/// <summary>
/// Logs every key and click TyriaPad emits, to tell it apart from input generated by other
/// programs (Steam Input, Armoury Crate SE). Mouse moves are not logged.
/// </summary>
public sealed class LoggingInputSink(IInputSink inner) : IInputSink
{
    private long _mouseDx;
    private long _mouseDy;

    /// <summary>Returns and resets the accumulated mouse movement (for the heartbeat).</summary>
    public (long Dx, long Dy) TakeMouseTotals() => (Interlocked.Exchange(ref _mouseDx, 0), Interlocked.Exchange(ref _mouseDy, 0));

    public void SendKey(Key key, bool down)
    {
        Log.Write($"Sent: {key} {(down ? "down" : "up")}");
        inner.SendKey(key, down);
    }

    public void SendMouseButton(MouseButton button, bool down)
    {
        Log.Write($"Sent: click {button} {(down ? "down" : "up")}");
        inner.SendMouseButton(button, down);
    }

    public void SendMouseMove(int dx, int dy)
    {
        Interlocked.Add(ref _mouseDx, dx);
        Interlocked.Add(ref _mouseDy, dy);
        inner.SendMouseMove(dx, dy);
    }

    public void SendMouseWheel(int delta)
    {
        Log.Write($"Sent: wheel {delta}");
        inner.SendMouseWheel(delta);
    }
}